"use client";
import React, { useState, useEffect, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import TalkCard from "@/components/TalkCard";
type Category = "All" | "Conferences" | "Talks";
const CATEGORY_DESCRIPTIONS = {
  All: "A showcase of talks and conferences by the talented members of Point Blank.",
  Conferences:
    "Our members representing Point Blank on global stages and major tech summits.",
  Talks:
    "Internal deep-dives, community workshops, and technical sharing sessions.",
};
const TALKS_DATA = [
  {
    id: "talk-1",
    name: "Ashutosh Pandey",
    title:
      "Security-Aware Prompting Alone Does Not prevent Crashes in LLM-Generated C Code",
    date: "December 2025",
    conference: "FSTTCS Conference",
    location: "@Bits Pilani, K K Birla Campus",
    description:
      "At the CSS Workshop co-located with the FSTTCS Conference in Goa, Ashutosh Pandey presented an experimental investigation into the reliability of LLM-generated C code. The talk demonstrated that security-aware prompting alone does not consistently prevent crashes or unsafe behaviors, and analyzed how factors such as prompt structure, example guidance, temperature, and programming language choice influence model failure patterns. The presentation highlighted deeper concerns around robustness, evaluation methodology, and the limits of prompt-based safeguards in safety-critical code generation contexts.",
    type: "Talks",
    links: [
      {
        label: "See post",
        url: "https://www.linkedin.com/posts/ashupdsce_iarcs-fsttcs-compilers-activity-7425917422446186497-b89f?utm_source=share&utm_medium=member_desktop&rcm=ACoAAGBiLHYBtbgKjG7JauXMP3ngSHikCXqHbBo",
      },
    ],
  },
  {
    id: "talk-2",
    name: "Kamini Banait, Madhur Kumar, Prajwal KP",
    title:
      "Comparative Analysis of Intermediate Representations for Security Tasks",
    date: "December 2025",
    conference: "FSTTCS Conference",
    location: "@Bits Pilani, K K Birla Campus",
    description:
      "During the CSS Workshop at the FSTTCS Conference, Kamini Banait, Madhur Kumar, and Prajwal K P delivered a research-focused talk exploring the behavior and analytical consequences of intermediate representations generated by tools like Ghidra and P-code. The session dissected structural and semantic variations across IRs, discussed their relevance to binary analysis and lifting accuracy, and reflected on the complexities of translating machine-level constructs into analyzable abstractions. Their work sparked technical discussions on correctness, abstraction fidelity, and security analysis strategies.",
    type: "Talks",
    links: [],
  },
  {
    id: "talk-3",
    name: "Pratik Singh",
    title: "Terraform Terrors Tamed: A GitOps Tale with KCL Magic",
    date: "April 2025",
    conference: "DevOpsDays Geneva",
    location: "@Geneva, Switzerland",
    description:
      "Pratik Singh delivered a practical session on transforming common Terraform pitfalls into robust, policy-compliant Infrastructure as Code using GitOps and KCL (Kubernetes Configuration Language). He walked through how teams can leverage KCL to validate Terraform plans against organizational policies early in the development lifecycle, enforce least-privilege resource definitions, and prevent misconfigurations that lead to security or compliance issues. The talk emphasized integrating this validation into GitOps workflows to automate error detection, improve governance, and increase confidence in IaC deployments.",
    type: "Talks",
    links: [
      {
        label: "Watch Recording",
        url: "https://youtu.be/Ua61L_KfNBA?si=BppseNtIyZZtPcs0",
      },
      {
        label: "See post",
        url: "https://www.linkedin.com/posts/kitarp29_devopsdaysgeneva-devops-terraform-activity-7339996354502397952-aHUT?utm_source=share&utm_medium=member_desktop&rcm=ACoAAGBiLHYBtbgKjG7JauXMP3ngSHikCXqHbBo",
      },
    ],
  },
  {
    id: "talk-4",
    name: "Pratik Singh",
    title: "The Future of CI/CD: Continuous Code Quality using AI",
    date: "April 2025",
    conference: "FOSSASIA Summit 2025",
    location: "@Bangkok",
    description:
      "Pratik Singh spoke about the evolving landscape of CI/CD where continuous code quality becomes a core focus, especially with AI becoming an integral part of developer toolchains. He explored how modern CI/CD pipelines can integrate automated AI-driven quality checks — from intelligent code suggestions and static analysis to vulnerability detection and test automation — to improve software reliability and reduce manual QA overhead. Singh highlighted the challenges and opportunities of combining AI with traditional DevOps practices to create feedback-rich, quality-centric deployment workflows.",
    type: "Talks",
    links: [
      {
        label: "Watch Recording",
        url: "https://youtu.be/tAWS_3PINuU?si=vz9bCFR37GWR8MVU",
      },
      {
        label: "See post",
        url: "https://www.linkedin.com/posts/kitarp29_fossasiasummit2025-cicd-ai-activity-7306920911675265024-aN6a?utm_source=share&utm_medium=member_desktop&rcm=ACoAAGBiLHYBtbgKjG7JauXMP3ngSHikCXqHbBo",
      },
    ],
  },
  {
    id: "talk-5",
    name: "Pratik Singh",
    title:
      "Ease the Pain of Platform Engineers with Argo CD by Leveraging Kustomize Templates",
    date: "April 2024",
    conference: "GitOps Con",
    location: "@GitOpsCon North America",
    description:
      "Pratik Singh delivered a talk on reducing the operational burden of platform engineers by leveraging Argo CD together with reusable Kustomize templates. He outlined how template-driven configuration can cut down on repetitive YAML creation and how combining this with Argo CD’s GitOps model allows teams to standardize application deployments while enabling self-service onboarding. The session explained the role of App Project RBAC in empowering developers to customize and deploy applications independently, improving consistency, productivity, and predictability across Kubernetes deployment workflows.",
    type: "Talks",
    links: [
      {
        label: "Watch Recording",
        url: "https://youtu.be/kp4XOShQWSU?si=N6eK0_z2eEpTFqMo",
      },
      {
        label: "See post",
        url: "https://www.linkedin.com/posts/kitarp29_gitopscon-kubernetes-argocd-activity-7185986291442843649-B432?utm_source=share&utm_medium=member_desktop&rcm=ACoAAGBiLHYBtbgKjG7JauXMP3ngSHikCXqHbBo",
      },
    ],
  },

  {
    id: "talk-6",
    name: "Ashutosh Pandey",
    title: "IndiaFOSS: Scaling a niche community to 1900 and beyond!",
    date: "October 2024",
    conference: "IndiaFOSS 2024",
    location: "@Bengaluru",
    description:
      "Ashutosh Pandey delivered an engaging session on growing a specialized tech community around compilers, programming languages, and systems from small beginnings to nearly 2000 engaged members. He shared strategies for community building, including regular meetups, active collaboration, inclusive engagement practices, and leveraging online platforms to sustain momentum. Through real-world anecdotes and lessons learned, the talk highlighted how consistency, clear purpose, and supportive environments can help scale niche technical communities effectively, inspiring contributors to connect, learn, and grow together.",
    type: "Talks",
    links: [
      {
        label: "Watch Recording",
        url: "https://youtu.be/wegPULgNDWI?si=z7u_LLvQd5ApSGtv",
      },
    ],
  },
];

export default function TalksPage() {
  const [activeCategory, setActiveCategory] = useState<Category>("All");
  const [isInitialRender, setIsInitialRender] = useState(true);
  const [selectedTalk, setSelectedTalk] = useState<any | null>(null);

  useEffect(() => {
    const timer = setTimeout(() => setIsInitialRender(false), 3000);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") setSelectedTalk(null);
    };

    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  useEffect(() => {
    if (selectedTalk) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
  }, [selectedTalk]);

  const filteredTalks = useMemo(() => {
    return activeCategory === "All"
      ? TALKS_DATA
      : TALKS_DATA.filter((talk) => talk.type === activeCategory);
  }, [activeCategory]);

  return (
    <main className="min-h-screen bg-black text-white relative flex flex-col font-sans overflow-x-hidden">
      <div
        className="w-full h-[220px] md:h-[280px] flex-shrink-0"
        aria-hidden="true"
      />

      <div className="fixed top-0 left-1/4 w-96 h-96 bg-green-500/10 rounded-full blur-[120px] -z-10" />
      <div className="fixed bottom-0 right-1/4 w-96 h-96 bg-green-500/5 rounded-full blur-[120px] -z-10" />

      <div className="max-w-7xl mx-auto pb-20 px-6 relative z-10 w-full flex flex-col items-center">
        <header className="relative mb-24 text-center">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-5xl md:text-7xl font-extrabold tracking-tighter uppercase"
          >
            We Speak. We Share. We Lead.
          </motion.h1>
          <motion.p
            key={activeCategory} // Adding a key makes the text animate when it changes
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="text-lg md:text-xl text-zinc-500 mt-6 italic"
          >
            {CATEGORY_DESCRIPTIONS[activeCategory]}
          </motion.p>
        </header>

        <div className="flex flex-wrap justify-center gap-4 mb-20">
          {(["All", "Conferences", "Talks"] as Category[]).map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-8 py-2.5 rounded-full font-bold text-sm transition-all duration-300 ${
                activeCategory === cat
                  ? "bg-[#00C853] text-black shadow-[0_0_25px_rgba(0,200,83,0.5)] scale-105"
                  : "bg-zinc-900/80 text-zinc-500 hover:text-zinc-200 border border-zinc-800"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 w-full">
          <AnimatePresence mode="popLayout">
            {filteredTalks.map((talk, idx) => (
              <motion.div
                key={talk.id}
                layout
                onClick={() => setSelectedTalk(talk)}
                className="cursor-pointer"
                initial={{ opacity: 0, scale: 0.95, y: 30 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{
                  duration: 0.4,
                  delay: isInitialRender ? idx * 0.1 : 0,
                }}
              >
                <TalkCard talk={talk} />
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </div>
      <AnimatePresence>
        {selectedTalk && (
          <>
            {/* Dark Backdrop Overlay */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedTalk(null)}
              className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[100]"
            />
            {/* Modal */}
            <motion.div
              initial={{ opacity: 0, scale: 0.92 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.92 }}
              transition={{ duration: 0.2, ease: "easeOut" }}
              className="fixed inset-0 z-[101] flex items-center justify-center p-6"
            >
              <div
                onClick={(e) => e.stopPropagation()}
                className="relative w-full max-w-2xl bg-zinc-950 border border-zinc-800 
               rounded-2xl p-8 shadow-[0_0_60px_rgba(0,0,0,0.8)]"
              >
                <button
                  onClick={() => setSelectedTalk(null)}
                  className="absolute top-5 right-5 text-zinc-500 hover:text-white text-xl"
                >
                  ✕
                </button>

                <p className="text-[#00C853] font-bold text-xs uppercase tracking-widest mb-2">
                  {selectedTalk.type}
                </p>

                <h2 className="text-3xl font-extrabold text-white leading-tight">
                  {selectedTalk.title}
                </h2>

                <div className="mt-4 text-zinc-400 font-medium flex flex-wrap items-center gap-2">
                  <span>{selectedTalk.name}</span>
                  <span>•</span>
                  <span>{selectedTalk.conference}</span>
                  <span>•</span>
                  <span className="text-[#00C853]">{selectedTalk.date}</span>
                </div>

                <div className="mt-10 space-y-6">
                  <div>
                    <h4 className="text-zinc-500 uppercase text-[10px] font-bold tracking-widest mb-2">
                      Location
                    </h4>
                    <p className="text-lg text-zinc-200">
                      {selectedTalk.location}
                    </p>
                  </div>

                  <div>
                    <h4 className="text-zinc-500 uppercase text-[10px] font-bold tracking-widest mb-2">
                      Description
                    </h4>
                    <p className="text-zinc-300 leading-relaxed">
                      {selectedTalk.description}
                    </p>
                  </div>
                  {selectedTalk.links?.length > 0 && (
                    <div>
                      <h4 className="text-zinc-500 uppercase text-[10px] font-bold tracking-widest mb-3">
                        Links
                      </h4>

                      <div className="flex flex-wrap gap-3">
                        {selectedTalk.links.map((link: any, idx: number) => (
                          <a
                            key={idx}
                            href={link.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-4 py-2 text-sm rounded-lg bg-zinc-900 border border-zinc-800 
                     text-zinc-300 hover:text-black hover:bg-[#00C853] 
                     transition-all duration-300"
                          >
                            {link.label}
                          </a>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </main>
  );
}
