export const achievementJson = [
  {
    id: 1,
    name: "Pratyush Singh",
    username: "@GSOC",
    body: "The Mifos Initiative",
    img: "gsoclogo.webp",
  },
  {
    id: 2,
    name: "Ashutosh Pandey",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 3,
    name: "Mohit Agarwal",
    username: "@ICPC",
    body: "ACM-ICPC Regionalist",
    img: "icpclogo.webp",
  },
  {
    id: 4,
    name: "Debayan G",
    username: "@SIH",
    body: "Winner OF SIH’23",
    img: "sihlogo.webp",
  },
  {
    id: 5,
    name: "Rahul Jagwani",
    username: "@GSOC",
    body: "Global Alliance for Genomics and Health",
    img: "gsoclogo.webp",
  },
  {
    id: 6,
    name: "Saalim Quadri",
    username: "@LFX",
    body: "Linux Kernel Mentorship Program",
    img: "lfxlogo.webp",
  },
  {
    id: 7,
    name: "Soumya Pattanayak",
    username: "@ICPC",
    body: "First team to qualify to ICPC regionals from DSCE",
    img: "icpclogo.webp",
  },
  {
    id: 8,
    name: "Akash Singh",
    username: "@HackGlobal",
    body: "Winner of HackBangalore | Top 9 in HackGlobal",
    img: "hackglobal.webp",
  },
  {
    id: 9,
    name: "Uttkarsh",
    username: "@GSOC",
    body: "OWASP Foundation",
    img: "gsoclogo.webp",
  },
  {
    name: "Aayush Kumar",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 10,
    name: "Priyanshu Gupta",
    username: "@ICPC",
    body: "ACM-ICPC Regionalist",
    img: "icpclogo.webp",
  },
  {
    id: 11,
    name: "Madhur Mehta",
    username: "@SIH",
    body: "Winner OF SIH’23",
    img: "sihlogo.webp",
  },
  {
    id: 12,
    name: "Akash Singh",
    username: "@GSOC",
    body: "Keploy: E2E test generation",
    img: "gsoclogo.webp",
  },
  {
    id: 13,
    name: "Tanmay R K",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 14,
    name: "Aditya",
    username: "@GSOC",
    body: "The Mifos Initiative",
    img: "gsoclogo.webp",
  },
  {
    id: 15,
    name: "Abhyuday Hari",
    username: "@HackGlobal",
    body: "Winner of HackBangalore | Top 9 in HackGlobal",
    img: "hackglobal.webp",
  },
  
  {
    id: 16,
    name: "Pratik Singh",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 17,
    name: "Palak Khandelwal",
    username: "@SIH",
    body: "Winner OF SIH’23",
    img: "sihlogo.webp",
  },
  {
    id: 18,
    name: "Bhuvan M",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 19,
    name: "Ankit Kumar Singh",
    username: "@Centuriton",
    body: "Winner OF CentuRITon'22",
    img: "centuriton.webp",
  },
  {
    id: 20,
    name: "Abhyuday Hari",
    username: "@LFX",
    body: "LiFT Scholarship Holder",
    img: "lfxlogo.webp",
  },
  {
    id: 21,
    name: "Sreeniketh Madugula",
    username: "@Centuriton",
    body: "Winner OF CentuRITon'22",
    img: "centuriton.webp",
  },    
  {
    id: 22,
    name: "Akash Singh",
    username: "@NITK Hackverse",
    body: "Grand Winner Of Nitk Hackverse '25",
    img: "nitklogo.webp",
  },
  {
    id: 23,
    name: "Alfiya Fatima",
    username: "@Genesys",
    body: "2nd Runner Up at PES University hackathon",
    img: "genesys.webp",
  },
  {
    id: 24,
    name: "Bhoomi Agarwal",
    username: "@SIH",
    body: "Winner OF SIH’24",
    img: "sihlogo.webp",
  },
  {
    id: 25,
    name: "Tushar Mahopatra",
    username: "@Aegis Sandbox",
    body: "3rd Place Winner at Sandbox hackathon",
    img: "Aegis.webp",
  },
  {
    id: 26,
    name: "Yusuf Azam",
    username: "@ICPC",
    body: "ACM-ICPC Regionalist",
    img: "icpclogo.webp",
  },
  {
    id: 27,
    name: "Chetan R",
    username: "@Genesys",
    body: "2nd Runner Up at PES University hackathon",
    img: "genesys.webp",
  },
  {
    id: 28,
    name: "Dhruv Puri",
    username: "@NITK Hackverse",
    body: "Grand Winner Of Nitk Hackverse '25",
    img: "nitklogo.webp",
  },
  {
    id: 29,
    name: "Prajwal K P",
    username: "@SIH",
    body: "Winner OF SIH'24",
    img: "sihlogo.webp",
  },
];
